module.exports = {
  INPUT_TEXT: 'INPUT_TEXT',
  INPUT_NUMBER: 'INPUT_NUMBER',
  INPUT_IMAGE: 'INPUT_IMAGE', 
  MULTI_SELECT_INGREDIENTS: 'MULTI_SELECT_INGREDIENTS',
  PIZZA_SIZES: 'PIZZA_SIZES',
  SWITCH: 'SWITCH',
};
